# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Stage 1: Build
FROM node:lts-alpine AS builder
WORKDIR /app

# Install deps
COPY package.json package-lock.json ./
RUN npm install

# Copy sources and build
COPY . ./
RUN npm run build

# Stage 2: Production image
FROM node:lts-alpine
WORKDIR /app

# Copy built artifacts and package files
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

# Install production dependencies only
RUN npm install --production

# Default command
CMD ["node", "dist/index.js"]
